### ISSUE TITLE
Roadmap for casbin-rs@1.0.0

### ISSUE THREAD

**Issue by xcaptain** [casbin/casbin-rs#5]
Todo list for the v1.0 release

- [x] Optimize `model.rs`, add more tests @GopherJ #8 
- [x] Optimize `rbac.rs`, implement `get_roles` and `get_users` method @xcaptain  #7 #9 
- [x] Setup travis and codecov @hsluoyz 
- [x] Check whether domain can have a length more than 2 strings. This affects if we should define domain as `Option<&str>` or `Vec<&str>` @hsluoyz 
- [x] Implement RBAC apis for enforcer @xcaptain  #14 #20 
- [x] Add clippy to travis-ci and fix clippy warnings @GopherJ #15 #16 
- [x] Add `autoSave`, `autoBuildRoleLink` option in enforcer @xcaptain #17 
- [x] Investigate how to use variadic parameters in rust. e.g. `enforce`, `generate_g_function`, `add_permission_for_user`and so on. Currently we are using Vector to store those parameters, but this way is not elegant @xcaptain #22 
- [x] Refactor api structure. #29 
- [x] Rename the package name. #30 
- [x] Default implement some APIs for Enforcer. #31 
- [x] Create model from file directly for easy of use. #32 
- [x] Better error handling. #24 
- [x] Create a diesel adapter
- [x] Investigate how to replace a boxed trait at runtime. e.g. replace `e.adapter` with a new adapter at runtime. @DevinR528
- [x] Fix module visibility, remove unnessarry `pub`
- [x] Add benchmark @GopherJ @DevinR528 
- [x] Investigate how to parse `in` operator in config file @GopherJ 
- [x] Automatically publish package to crate.io when a new git tag is created
- [x] Add cache support (@GopherJ  @xcaptain ) #45 
- [x] Add watcher support (@GopherJ   @xcaptain ) #46 
- [x] Add async-std support (low priority @GopherJ @xcaptain ) #43
- [x] Implement a `FilteredAdapter` #79 
- [x] Implement ABAC model #78 
People who want to contribute please reply to this issue, apply for a task and then make a pull request.

**Comment by GopherJ** [comment]
:thumbsup: @xcaptain

> Create a postgresql adapter
> A demo project using postgresql and actix-web

**Comment by XanthusL** [comment]
>investigate how to pass variadic paramaters to rhai expressions, rbac_with_domains_model.conf takes 3 parameters

From my perspective, we can use a builder or enum for it.

**Comment by hsluoyz** [comment]
@GopherJ @xcaptain , do you know anyone that can be Casbin's MOSS champion? He/she should be **an established member of the Mozilla community who knows/uses Casbin**.

See `What a Mozilla champion does` section in: https://www.mozilla.org/en-US/moss/foundational-technology/

**Comment by GopherJ** [comment]
@hsluoyz sorry, currently no for me.

**Comment by GopherJ** [comment]
There are still many works to do. If any one wants to pick one of them:

https://github.com/casbin-rs

We are already not far from casbin-rs@1.0

**Comment by andrewbanchich** [comment]
@hsluoyz Just FYI, Rust was originally incubated by Mozilla but it then was taken over as it's only community-driven project. There are still some ties it has to Mozilla, but it isn't really something I would say is developed by Mozilla.

**Comment by omid** [comment]
Isn't the "Create a postgresql adapter" finished [here](https://github.com/casbin-rs/diesel-adapter)?

**Comment by DevinR528** [comment]
> Investigate how to replace a boxed trait at runtime. e.g. replace e.adapter with a new adapter at runtime. 

would the use of this look something like this
```rust
let adpt = FileAdapter::new("examples/basic_policy.csv");
let adpt2 = MemoryAdapter::default();
let model = DefaultModel::from_file("examples/rbac_model.conf").await.unwrap();
let mut e = Enforcer::new(Box::new(model), Box::new(adpt)).await.unwrap();
// swap adaptor 
e.set_adapter(Box::new(adpt2));
```
and the same for `Model` but you may have to `reload_policy`?

**Comment by xcaptain** [comment]
@DevinR528 Yes, we can do this way because `Box<dyn Adapter>` removes type information, at first we are using 

```rust
pub struct Enforcer<A: Adapter> {
    pub adapter: A,
    // ..
}
```

So we were facing the problem that can't change adapter at runtime.

**Comment by DevinR528** [comment]
Ahh yeah the whole existential type stuff being much less limited with `Box<dyn Trait>`.

I was planning on opening a few PR's to work on the roadmap if that sounds good, I'll reference this issue.

**Comment by hackerchai** [comment]
@xcaptain @hsluoyz 
I am currently working on the (sqlx-adapter)[https://github.com/casbin-rs/sqlx-adapter] development which will fully support async database operation.

**Comment by GopherJ** [comment]
close this as nearly all items are checked. See #119 for latest filtered adapter
